import urllib.request
import xlrd3 as xlrd
import json


DATA_URL = "http://www.musztydobay.hu/osszescsalidalexcel.xls"


def download_data(url):
    """Download data from URL and return in binary-string"""
    response = urllib.request.urlopen(url)
    data = response.read()
    return data


def extract_from_excel_blob(data):
    """Open binary blob xls and return data from first sheet in list of strings"""
    book = xlrd.open_workbook(file_contents = data)
    sh = book.sheet_by_index(0)
    for rx in range(sh.nrows):
        yield [cx.value for cx in sh.row(rx)]


def convert_to_json_data(data):
    """Convert list of strings to json format"""
    if next(data) != ['Dal neve', 'Előadó', 'Könyv', 'Akkord', 'Akkord száma']:
        raise ValueError("Check input. Might be broken.")
    for title, performer, pages, chords, _ in data:
        print(title)
        yield dict(
            title=title,
            performer=performer,
            pages=pages,
            chords=chords,
        )


def export_json(data, fname):
    """Export json data to file"""
    data = list(data)
    with open(fname, "w") as fp:
        fp.write("//Autogenerated do not modify\n\nexport const CHORDINFO = " + json.dumps(data, indent=4, sort_keys=True) + ";")


def main():
    data = download_data(DATA_URL)
    data = extract_from_excel_blob(data)
    data = convert_to_json_data(data)
    export_json(data, "../../chordinfo.js")


if __name__ == "__main__":
    main()
